### PR TITLE
Hello World using Applets

### PR DESCRIPTION
**Pull request by syedzubeen**

### CODE REVIEW

**Review by NachiketaVadera — CHANGES_REQUESTED** [review]
Please indent the code properly. Thank you!

**Comment by NachiketaVadera** [comment]
@syedzubeen Thank you for your interest. Please make the requested change.

**Review by NachiketaVadera — CHANGES_REQUESTED** [review]
Also, make the class name same as the file name. Thanks.

**Comment by syedzubeen** [comment]
done 👍🏻

**Review by NachiketaVadera — APPROVED** [review]
Thank you!

**Comment by NachiketaVadera** [comment]
@syedzubeen Thank you for your contribution 😁

**Pull request merged**
