### PR TITLE
Added implementation that uses Reflection

### PR DESCRIPTION
**Pull request by apol657**
Made for issue #35 

The point of this implementation was to instantiate objects and invoke methods via Java Reflection.
One can see the power this feature can offer, but also the dangers of it (almost everything can throw an Exception when using Reflection).

### CODE REVIEW

**Review by NachiketaVadera — COMMENTED** [review]
@apol657 Hey. Thank you for you interest. While executing the code, I had a deprecation warning that read as follows:
```
Main.java:14: warning: [deprecation] newInstance() in Class has been deprecated
        Object parentInstance = parentClass.newInstance();
                                           ^
  where T is a type-variable:
    T extends Object declared in class Class
Main.java:34: warning: [deprecation] newInstance() in Class has been deprecated
            StringBuilder stringBuilder = (StringBuilder) stringBuilderClass.newInstance();
                                                                            ^
  where T is a type-variable:
    T extends Object declared in class Class
2 warnings
```
Do you know any newer method to solve this? 

**Note: For execution, the class name was changed to Main.**

**Comment by apol657** [comment]
Oh I was using Java8, so I did not have that warning. It seems with Java11 the non-deprecated way is to use class.getDeclaredConstructor().newInstance(); I will be pushing a commit for it soon.

**Comment by apol657** [comment]
By the way, if the class name is changed, it must be changed wherever it is mentioned within various Strings. There are two cases, at lines 9 and 13.

**Comment by NachiketaVadera** [comment]
@apol657 Great! Thank you for your contribution.

**Pull request merged**
