### PR TITLE
Search a character in String "Hello World" via Linear/Binary search in Java #65

### PR DESCRIPTION
**Pull request by VarunVishwakarma117**
scanning char using a scanner and comparing each char of string with scanned char.
I've used if-else to make the output look better.
I apologize , if I haven't placed the file in right place.

### CODE REVIEW

**Review by NachiketaVadera — CHANGES_REQUESTED** [review]
Hey! Thank you for your interest. A couple of changes and this branch will be ready to merge in.

- For characters not in the string, you get this empty looking output instead of a message like `char in not in the string`.
image

- In `HelloWorld_YourWay`, the `YourWay` part is supposed to be replaced with your implementation of Hello World. Like `HelloWorld_LinearSearch`. I'll make it more clear in the documentation! But please change it here. 

Thank you.

**Comment by VarunSharma117** [comment]
I've fixed issue #65 please review it.

**Comment by VarunSharma117** [comment]
I've added a new program to search a char using binarySearch Case Sensitive and fix the issue in the first program. Please review it.

**Comment by VarunSharma117** [comment]
please review it

**Pull request closed without merging**
