### PR TITLE
Create HelloWorld_Using_if_else_array.java

### PR DESCRIPTION
**Pull request by Roshanpaswan**
Printed hello world using if-else statement and array

### CODE REVIEW

**Comment by NachiketaVadera** [comment]
@Roshanpaswan Hey! Thank you for your interest. Could you please change the class name so that it reflects the file name?

**Review by NachiketaVadera — CHANGES_REQUESTED** [review]
Please implement the following change. 
- [ ] Make the file name same as the class name.

**Comment by NachiketaVadera** [comment]
@Roshanpaswan Thank you!

**Comment by Roshanpaswan** [comment]
Can you please add hacktoberfest-accepted label in this pull request it will very helpful for me.Please!.

**Pull request merged**
